//
// Created by apha on 2017.10.11..
//

#ifndef CPP_MIGHTY_TEXT_ADVENTURE_RETURN_FUNNYTEAMNAME_ACTIONTYPE_H
#define CPP_MIGHTY_TEXT_ADVENTURE_RETURN_FUNNYTEAMNAME_ACTIONTYPE_H


enum class ActionType {
    INVALID_ENTRY, NORTH, SOUTH, EAST, WEST, ATTACK, EQUIP, UNEQUIP, DROP, USE
};


#endif //CPP_MIGHTY_TEXT_ADVENTURE_RETURN_FUNNYTEAMNAME_ACTIONTYPE_H
