//
// Created by apha on 2017.10.11..
//

#ifndef CPP_MIGHTY_TEXT_ADVENTURE_RETURN_FUNNYTEAMNAME_ITEMTYPE_H
#define CPP_MIGHTY_TEXT_ADVENTURE_RETURN_FUNNYTEAMNAME_ITEMTYPE_H


enum class ItemType {
    KEY, CONSUMABLE, WEAPON, SHIELD, ARMOR
};


#endif //CPP_MIGHTY_TEXT_ADVENTURE_RETURN_FUNNYTEAMNAME_ITEMTYPE_H
