//
// Created by András on 2017. 10. 12..
//

#ifndef CPP_MIGHTY_TEXT_ADVENTURE_RETURN_FUNNYTEAMNAME_USEEFFECTTYPE_H
#define CPP_MIGHTY_TEXT_ADVENTURE_RETURN_FUNNYTEAMNAME_USEEFFECTTYPE_H


enum class UseEffectType {
    NONE, HEAL, OPEN_DOOR
};


#endif //CPP_MIGHTY_TEXT_ADVENTURE_RETURN_FUNNYTEAMNAME_USEEFFECTTYPE_H
